// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jvlhtsqeqnzdzxfrehlx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2bGh0c3FlcW56ZHp4ZnJlaGx4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNjk5OTksImV4cCI6MjA2MDY0NTk5OX0.SQpsPNaS-_ntImr_bA1VXm0C3s7NzZ6Z7GLs_w35B3E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);